### ISSUE TITLE
🐛 수정된 센터 검색 API가 기존 방식과 호환되도록 수정

### ISSUE THREAD

**Issue by uwoobeat** [FISOLUTION/BE_POLICE_PUBLIC#11]
## 🦾  Fix Description
- #10 에서 컨트롤러 코드 변경 후 프론트엔드에서 JSON 파싱 에러 발생
- 기존 Result 타입이 아닌 ResponseEntity를 사용하면서 DTO 스키마가 달라짐
- 기존 Result 타입이 반환하는 스키마를 충족하도록 수정
- 수정한 코드가 테스트 코드에서 정상적으로 작동하도록 수정
- 추가로 `visited` 필드 변경 요구사항 반영

## 📝  To-do
- [x] 컨트롤러 구현체 및 인터페이스의 반환 타입을 `ResponseEntity<>`에서 `ResponseEntity<Result<>>` 형태로 수정
- [x] visited 필드 제거 및 레포지터리 코드 수정
- [x] 테스트 코드 실행 오류 해결 위해 Result 클래스에 기본 생성자 추가
