### ISSUE TITLE
✨ 센터 검색 시 정렬 옵션 추가

### ISSUE THREAD

**Issue by uwoobeat** [FISOLUTION/BE_POLICE_PUBLIC#14]
## 📌 Feature Issue
- 센터 검색 시 정렬 옵션을 추가해야 합니다.
- 다음 정렬 옵션이 가능해야 합니다.
    - 총 재원생 수 기준 오름차순 / 내림차순 정렬
    - 지문사업 참여여부 기준 오름차순 / 내림차순 정렬

## 📝 To-do
- [ ] 총 재원생 수 기준 오름차순 / 내림차순 정렬 구현
- [ ] 지문사업 참여여부 기준 오름차순 / 내림차순 정렬 구현
- [ ] 각 정렬 로직에 대한 테스트 추가 및 검증
