### ISSUE TITLE
✨ 센터 검색 API가 총 재원생 수를 반환하도록 수정

### ISSUE THREAD

**Issue by uwoobeat** [FISOLUTION/BE_POLICE_PUBLIC#7]
## 📌 Feature Issue
- 센터 검색 api가 총 재원생 수 필드를 추가로 반환하도록 수정하기

## 📝 To-do
- [x] 컨트롤러, DTO 코드 수정
- [x] 서비스 코드 수정
- [x] 테스트 코드 추가
